export { default as Personal } from './Personal'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Contact } from './Contact'
export { default as Signup } from './Signup'